### ISSUE TITLE
List of Active apps in portal

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#724]
## Expected outcome

```
GET /api/portal/{portalId}/all-apps
```
We need a endpoint to get all Applications available for the given portal.
the endpoint also need to return and indicator that a Application is activated on the portal.
The apps return should be filtered by the portals context Type configuration
```
 {
    "key": "string",
    "contextTypes": [
      {
        "type": "string"
      }
    ],
    "isActive": "boolean",
    "portalAppType": "GlobalApp" | "ContextApp",
    "appManifest": {
       // Fusion app manifest
    }
  }
```

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by kjetilhau** [comment]
@Jossilainen @Noggling 

A few thoughts:

- ``PortalAppType`` is not a concept we have other places in the backend. What we do have is: IsGlobal and IsContextual. I suggest to use one of these instead so that we don't introduce more logic.
- The endpoint name ``GET /api/portal/{portalId}/all-apps`` is a little abstract. 
If this endpoint always will list out all onboarded apps (with more data from the portal), I would consider calling it ``GET /api/portal/{portalId}/onbarded-apps`` - because that is really what it is in that case.
 The difference would be that we will merge more information from the portal specifics to show which of these onboarded apps are active in this specific portal, etc.

**Comment by Jossilainen** [comment]
Comments @Noggling? I agree that the name: ``GET /api/portal/{portalId}/onboarded-apps`` is more precise.

**Comment by Noggling** [comment]
Great @kjetilhau
